# Generated by Django 5.2.17 on 2026-10-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('otp_expiry_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('session_inactivity_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('login_max_attempts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('login_lockout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('password_min_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('registration_requires_approval', models.BooleanField(blank=True, null=True)),
                ('email_notifications_enabled', models.BooleanField(blank=True, null=True)),
                ('viewer_render_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('viewer_jpeg_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payments_enabled', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='platform_settings_single_row')],
            },
        ),
    ]
