# Generated by Django 5.2.17 on 2026-10-05 06:37

from django.db import migrations, models


def split_existing_names(apps, schema_editor):
    """Best-effort split of the existing display name: first word / last word (middle name stays empty)."""
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(first_name="").iterator():
        parts = user.full_name.split()
        if not parts:
            continue
        user.first_name = parts[0][:100]
        user.last_name = " ".join(parts[1:])[:100]
        user.save(update_fields=["first_name", "last_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_encrypt_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(split_existing_names, migrations.RunPython.noop),
    ]
