# Generated by Django 5.2.17 on 2026-10-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('registration_approved', 'Registration approved'), ('registration_rejected', 'Registration rejected'), ('access_granted', 'Access granted'), ('access_revoked', 'Access revoked'), ('payment_successful', 'Payment successful'), ('course_published', 'Course published'), ('security', 'Security'), ('new_registration', 'New registration'), ('access_requested', 'Access requested'), ('payment_received', 'Payment received')], max_length=32),
        ),
    ]
