# Generated by Django 5.2.17 on 2026-10-01 09:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('source', models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('admin_approval', 'Granted or approved by admin'), ('payment', 'Payment')], max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
