# Generated by Django 5.2.17 on 2026-10-01 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaccess',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courseaccess',
            index=models.Index(fields=['course', 'status'], name='access_cour_course__864332_idx'),
        ),
        migrations.AddIndex(
            model_name='courseaccess',
            index=models.Index(fields=['status', 'expires_at'], name='access_cour_status_318cba_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseaccess',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_access'),
        ),
    ]
