# Generated by Django 5.2.17 on 2026-10-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaccess',
            name='payment_required',
            field=models.BooleanField(default=False),
        ),
    ]
