# Generated by Django 5.2.17 on 2026-10-01 09:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('access_mode', models.CharField(choices=[('immediate', 'Immediate access'), ('manual_approval', 'Manual approval'), ('payment_required', 'Payment required')], default='manual_approval', max_length=24)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('access_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'access_mode'], name='courses_cou_status_08c944_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('access_mode', 'payment_required'), _negated=True), models.Q(('price_amount__isnull', False), ('price_amount__gt', 0)), _connector='OR'), name='course_paid_requires_positive_price'), models.CheckConstraint(condition=models.Q(('access_duration_days__isnull', True), ('access_duration_days__gt', 0), _connector='OR'), name='course_duration_positive')],
            },
        ),
    ]
