# Generated by Django 5.2.17 on 2026-10-01 09:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Uploaded, not yet validated'), ('validated', 'Validated'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('storage_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('page_count', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='courses.course')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', 'status'], name='resources_r_course__6bc438_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('file_size__gt', 0)), name='resource_size_positive'), models.CheckConstraint(condition=models.Q(('page_count__gt', 0)), name='resource_pages_positive')],
            },
        ),
    ]
