# Generated by Django 5.2.17 on 2026-10-01 09:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('watermark_id', models.CharField(max_length=16)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='view_activities', to='courses.course')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='view_activities', to='resources.resource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['student', '-viewed_at'], name='viewing_vie_student_9675a9_idx'), models.Index(fields=['resource', 'page_number'], name='viewing_vie_resourc_c69e92_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('page_number__gt', 0)), name='view_page_positive')],
            },
        ),
    ]
